name: Quality Assurance Testing

on:
  push:
    branches:
      - qa_test
jobs:
  # backend_pylint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v3
  
  #   - name: Set up Python "3.11"
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: "3.11"
  
  #   - name: Install backend dependencies
  #     working-directory: ./backend
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install pylint
  
  #   - name: Analyzing backend code with pylint
  #     working-directory: ./backend
  #     run: |
  #       pylint '*.py' --disable=C0114,C0115,C0116,C0301,R0903,E1102

  backend_endpoint_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python "3.11"
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Backend Test
      working-directory: ./backend/test
      run: |
        pytest --disable-warnings

  frontend_acceptance_criteria_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python "3.11"
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm install
        npm install cypress --save-dev
        npm install cypress-file-upload --save-dev
        npm install @popperjs/core --save
        
    - name: frontend Test
      run: |
        chmod 744 run_frontend_test.sh
        ./run_frontend_test.sh
